name: Update README Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate GitHub Stats SVG
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=40436michael&show_icons=true&theme=tokyonight&hide_border=true
          path: github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Langs SVG
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=40436michael&layout=compact&theme=tokyonight&hide_border=true&hide=jupyter%20notebook,html,css
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit SVG files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add *.svg
          git commit -m "Update GitHub Stats" || exit 0
          git push
